### ISSUE TITLE
Newsletter: Issue No. 6

### ISSUE THREAD

**Issue by jtoar** [redwoodjs/redwoodjs.com#620]
> Last installment:
> - Issue No. 5
> - Shipped March 10th, 2021
> - https://mailchi.mp/redwoodjs/all-the-redwoodjs-news-fit-to-print-issue-6162849?e=da5a12ab29

Issue to discuss the 6th installment of the newsletter. May or may not end up collaborating much here (between this, notion, etc). But here's a place for it if we do. Half the battle is just collecting links!

## Issue No. 6

Shipping: ~April

### Intro

- [ ] what's our update on the v1 RC? do we have to give one? seems like we do?

### Highlights
- [ ] Replaces Flash with react-hot-toast (#1856) 4a899b5 cannikin `v0.27`
  - PR: https://github.com/redwoodjs/redwood/pull/1856
  - docs: https://redwoodjs.com/docs/toast-notifications
  - migration guide: https://community.redwoodjs.com/t/redwood-flash-is-being-replaced-with-react-hot-toast-how-to-update-your-project-v0-27-0/1921
- [ ] Prisma v2.18.0 `v0.27`
  - David's highlights and changes:
    - > HIGHLIGHTS: Native Types are now stable, Prisma Migrate now works with cloud-hosted databases (requires additional config)
    - > CHANGES: prisma db push flags have been changed, Relation syntax will no longer be updated automatically (use yarn redwood prisma format)
  - release notes for v2.17 and 18: https://github.com/prisma/prisma/releases/tag/2.17.0, https://github.com/prisma/prisma/releases/tag/2.18.0
  - possibly breaking changes (see https://community.redwoodjs.com/t/redwood-v0-27/1920)
- [ ] Add per request global context `v0.27`
  - PR: https://github.com/redwoodjs/redwood/pull/1789
  - how do we want to talk about this and how much do we want to talk about this?
- [ ] Switch create-redwood-app template to TypeScript (#1810) 91cef20 peterp `v0.27`
  - PR: https://github.com/redwoodjs/redwood/pull/1810

---

- [ ] api-side logger — https://github.com/redwoodjs/redwood/pull/1937
  - uses [pino](https://getpino.io/#/)
  - forum: https://community.redwoodjs.com/t/redwood-logging-ideas/1046
- [ ] router `<Set wrap={...} />` — https://github.com/redwoodjs/redwood/pull/1898
  - no more layout rerendering https://github.com/redwoodjs/redwood/issues/267
- [ ] a11y router and tooling — https://github.com/redwoodjs/redwood/pull/1817
- [ ] (experimental) build the api side with esbuild — https://github.com/redwoodjs/redwood/pull/1948
  - peter: "speed is one of the greatest DX features"
- [ ] highlight our security practices? — https://github.com/redwoodjs/redwood/issues/1953
  - probably not but just throwing it out there
- [ ] setup i18n — https://github.com/redwoodjs/redwood/pull/1847
- [ ] cells: stale while fetch — https://github.com/redwoodjs/redwood/pull/1878
- [ ] new contributing workflow: `yarn rwt link`, haven't highlighted it yet
  - might be too technical / specific to contributors to highlight in something meant for a general audience?
- [ ] typescript
  - do we want to wait till this is done done?
- [ ] talk about CI (framework), and call for contributions? 

### Snippets

Not sure if we're still having a snippets section, but if we do...
- [ ] Allow prerendering NotFoundPage as 404.html (v0.27)
  - PR: https://github.com/redwoodjs/redwood/pull/1891
  - docs: https://github.com/redwoodjs/redwoodjs.com/pull/615

---

- [ ] supabase: scopes on sign up/In — https://github.com/redwoodjs/redwood/issues/1959
- [ ] storybook config — https://github.com/redwoodjs/redwood/issues/1595#issuecomment-794965117
  - that issue's not actually done, but might be. you can already do `web/src/storybook.main.js`

### Etc.
- [ ] are the code blocks legible enough?
  - currently using [carbon.now.sh](https://carbon.now.sh/). would be a good idea to nail down the config for this
